server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#configurar o caminho logo será localhost:8060/employee/anithing ***, direcionando as requests
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
        - id: deparment-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
